# This file is automatically generated from blender_manifest.toml
#
# Generated with: $ generate_info.py blender_manifest.toml __jiggle_info.py
#

jiggle_info = {
    'name': 'Jiggle Physics',
    'description': 'Add stretchy jiggle physics to your Blender rigs',
    'author': 'naelstrof <naelstrof@gmail.com>',
    'blender': (4, 2, 0),
    'version': (4, 2, 0),
    'wiki_url': 'https://github.com/naelstrof/blender-jiggle-physics',
}
